### ISSUE TITLE
Coding style about zsudo.

### ISSUE THREAD

**Issue by MouriNaruto** [M2Team/zsudo#1]
@fcharlie  You said that we should use the LLVM coding style in the zsudo project.

But I have some suggestions about that.
1. We should set the standard limit for code width. (For example, 80 characters limit.)
2. Use 4 spaces indentation.
3. Place braces on separate lines.

Mouri

**Comment by fcharlie** [comment]
See: [https://llvm.org/docs/CodingStandards.html](https://llvm.org/docs/CodingStandards.html)

**Comment by MouriNaruto** [comment]
I have read it. 1 and 2 have mentioned in the LLVM coding style.

I only need to care about the brace style and the naming style.

@fcharlie

**Comment by fcharlie** [comment]
Code gen by cmake (`zsudoversion.h`) 
```c++
/// Create by cmake, don't edit.
#ifndef ZSUDOVERSION_H
#define ZSUDOVERSION_H

#define ZSUDO_VERSION L"1.0.0"
#define ZSUDO_HASH L"cc0dc7219345b7002bf0072890f7b192844738c6"
#define ZSUDO_REFS L"refs/heads/master"

#define ZSUDO_APPNAME L"zsudo-1.0"

#endif

```
